package model;
// Generated 26/11/2015 19:49:54 by Hibernate Tools 4.3.1

/**
 * Game generated by hbm2java
 */
public class Game extends Model implements java.io.Serializable {

    private Integer idGame;
    private Stage stage;
    private Team teamByFkHome;
    private Team teamByFkVisitor;
    private int number;
    private Integer homeScore;
    private Integer visitScore;

    public Game() {
    }

    public Game(int number) {
        this.number = number;
    }

    public Game(Stage stage, Team teamByFkHome, Team teamByFkVisitor, int number, Integer homeScore, Integer visitScore) {
        this.stage = stage;
        this.teamByFkHome = teamByFkHome;
        this.teamByFkVisitor = teamByFkVisitor;
        this.number = number;
        this.homeScore = homeScore;
        this.visitScore = visitScore;
    }

    public Integer getIdGame() {
        return this.idGame;
    }

    public void setIdGame(Integer idGame) {
        this.idGame = idGame;
    }

    public Stage getStage() {
        return this.stage;
    }

    public void setStage(Stage stage) {
        this.stage = stage;
    }

    public Team getTeamByFkHome() {
        return this.teamByFkHome;
    }

    public void setTeamByFkHome(Team teamByFkHome) {
        this.teamByFkHome = teamByFkHome;
    }

    public Team getTeamByFkVisitor() {
        return this.teamByFkVisitor;
    }

    public void setTeamByFkVisitor(Team teamByFkVisitor) {
        this.teamByFkVisitor = teamByFkVisitor;
    }

    public int getNumber() {
        return this.number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public Integer getHomeScore() {
        return this.homeScore;
    }

    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }

    public Integer getVisitScore() {
        return this.visitScore;
    }

    public void setVisitScore(Integer visitScore) {
        this.visitScore = visitScore;
    }

}
