package model;
// Generated 26/11/2015 19:49:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person extends Model implements java.io.Serializable {

    private Integer idPerson;
    private String username;
    private String password;
    private Set championships = new HashSet(0);

    public Person() {
    }

    public Person(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public Person(String username, String password, Set championships) {
        this.username = username;
        this.password = password;
        this.championships = championships;
    }

    public Integer getIdPerson() {
        return this.idPerson;
    }

    public void setIdPerson(Integer idPerson) {
        this.idPerson = idPerson;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getChampionships() {
        return this.championships;
    }

    public void setChampionships(Set championships) {
        this.championships = championships;
    }

}
