package model;
// Generated 26/11/2015 19:49:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage extends Model implements java.io.Serializable {

    private Integer idStage;
    private Championship championship;
    private String name;
    private Integer nteams;
    private Set games = new HashSet(0);

    public Stage() {
    }

    public Stage(Championship championship, String name, Integer nteams, Set games) {
        this.championship = championship;
        this.name = name;
        this.nteams = nteams;
        this.games = games;
    }

    public Integer getIdStage() {
        return this.idStage;
    }

    public void setIdStage(Integer idStage) {
        this.idStage = idStage;
    }

    public Championship getChampionship() {
        return this.championship;
    }

    public void setChampionship(Championship championship) {
        this.championship = championship;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNteams() {
        return this.nteams;
    }

    public void setNteams(Integer nteams) {
        this.nteams = nteams;
    }

    public Set getGames() {
        return this.games;
    }

    public void setGames(Set games) {
        this.games = games;
    }

}
