package model;
// Generated 26/11/2015 19:49:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team extends Model implements java.io.Serializable {

    private Integer idTeam;
    private Championship championship;
    private String name;
    private Set gamesForFkHome = new HashSet(0);
    private Set gamesForFkVisitor = new HashSet(0);

    public Team() {
    }

    public Team(String name) {
        this.name = name;
    }

    public Team(Championship championship, String name, Set gamesForFkHome, Set gamesForFkVisitor) {
        this.championship = championship;
        this.name = name;
        this.gamesForFkHome = gamesForFkHome;
        this.gamesForFkVisitor = gamesForFkVisitor;
    }

    public Integer getIdTeam() {
        return this.idTeam;
    }

    public void setIdTeam(Integer idTeam) {
        this.idTeam = idTeam;
    }

    public Championship getChampionship() {
        return this.championship;
    }

    public void setChampionship(Championship championship) {
        this.championship = championship;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getGamesForFkHome() {
        return this.gamesForFkHome;
    }

    public void setGamesForFkHome(Set gamesForFkHome) {
        this.gamesForFkHome = gamesForFkHome;
    }

    public Set getGamesForFkVisitor() {
        return this.gamesForFkVisitor;
    }

    public void setGamesForFkVisitor(Set gamesForFkVisitor) {
        this.gamesForFkVisitor = gamesForFkVisitor;
    }

}
